run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  format: colored-line-number

linters:
  enable:
    - gofmt
    - goimports
    - golint
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

linters-settings:
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true